# Generated by Django 5.1.2 on 2025-01-10 22:51

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_post', models.ImageField(upload_to='Imagenes Blogs', verbose_name='Imagen')),
                ('title_post', models.CharField(max_length=255, verbose_name='Titulo Post')),
                ('descriptions_post', models.TextField()),
                ('content_post', tinymce.models.HTMLField(verbose_name='Contenido')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('slug_post', models.SlugField(blank=True, null=True, unique=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Estado Publicación')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
