# Generated by Django 5.1.2 on 2024-12-13 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallecidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condolencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Fotos Condolencias')),
                ('descripcion', models.CharField(max_length=255)),
                ('nombre_familiar', models.CharField(max_length=155)),
                ('nombre_fallecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallecido', to='fallecidos.fallecido')),
            ],
        ),
    ]
