# Generated by Django 5.1.2 on 2024-12-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallecidos', '0002_condolencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='condolencias',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=-2019),
            preserve_default=False,
        ),
    ]
