# Generated by Django 5.1.2 on 2024-12-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fallecidos', '0004_alter_condolencias_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condolencias',
            name='fecha_creacion',
        ),
    ]
