# Generated by Django 5.1.2 on 2024-12-17 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallecidos', '0005_remove_condolencias_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='condolencias',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
