# Generated by Django 5.1.2 on 2024-12-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallecidos', '0006_condolencias_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallecido',
            name='documento_identidad',
            field=models.CharField(choices=[('DNI', 'Documento de Identidad'), ('PST', 'Pasaporte')], default='DNI', max_length=3),
        ),
    ]
