# Generated by Django 5.1.5 on 2025-01-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallecidos', '0009_remove_condolencias_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condolencias',
            options={'verbose_name': 'Condolencia', 'verbose_name_plural': 'Condolencias'},
        ),
        migrations.AlterModelOptions(
            name='fallecido',
            options={'verbose_name': 'Fallecido', 'verbose_name_plural': 'Fallecidos'},
        ),
        migrations.AddField(
            model_name='fallecido',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
