# Generated by Django 5.1.5 on 2025-02-04 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsPlanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_plan', models.CharField(max_length=255, unique=True, verbose_name='Nombre Plan')),
                ('description_plan', models.TextField(verbose_name='Descripción del Plan')),
                ('price_plan', models.FloatField(verbose_name='Precio Plan')),
                ('state_plan', models.BooleanField(default=True)),
                ('date_create_plan', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='ModelsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=155, verbose_name='Nombre Producto')),
                ('descriptions_product', models.TextField(verbose_name='Descripción de Producto')),
                ('price_product', models.FloatField(verbose_name='Precio Producto')),
                ('stock_product', models.IntegerField()),
                ('state_product', models.BooleanField(default=True)),
                ('slug_product', models.SlugField(blank=True, max_length=255, unique=True)),
                ('date_create_product', models.DateField(auto_now_add=True)),
                ('planes', models.ManyToManyField(related_name='planes', to='catalogo.modelsplanes')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ModelsUrnas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_urna', models.CharField(choices=[('METAL', 'METAL'), ('MADERA', 'MADERA'), ('MARMOL', 'MARMOL')], default='MADERA', max_length=10, verbose_name='Material Urna')),
                ('nombre_urna', models.CharField(max_length=255, verbose_name='Nombre Urna')),
                ('price_urna', models.FloatField(verbose_name='Precio Urna')),
                ('stock_urna', models.IntegerField()),
                ('state_urna', models.BooleanField(default=True)),
                ('slug_urna', models.SlugField(blank=True, max_length=255, unique=True)),
                ('date_create_urna', models.DateField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urnas', to='catalogo.modelsproduct')),
            ],
            options={
                'verbose_name': 'Urna',
                'verbose_name_plural': 'Urnas',
            },
        ),
    ]
