# Generated by Django 5.1.2 on 2025-01-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsPlanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_plan', models.CharField(max_length=255, unique=True, verbose_name='Nombre Plan')),
                ('description_plan', models.TextField(verbose_name='Descripción del Plan')),
                ('price_plan', models.FloatField(verbose_name='Precio Plan')),
                ('state_plan', models.BooleanField(default=True)),
                ('date_create_plan', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='ModelsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=155, verbose_name='Nombre Producto')),
                ('descriptions_product', models.TextField(verbose_name='Descripción de Producto')),
                ('price_product', models.FloatField(verbose_name='Precio Producto')),
                ('category_product', models.CharField(choices=[('URNAS', 'URNAS'), ('IMPLEMENTOS', 'IMPLEMENTOS')], default='IMPLEMENTOS', max_length=15, verbose_name='Categoria de producto')),
                ('stock_product', models.IntegerField()),
                ('state_product', models.BooleanField(default=True)),
                ('slug_product', models.SlugField(blank=True, default='valor', max_length=255, null=True, unique=True)),
                ('date_create_product', models.DateField(auto_now_add=True)),
                ('planes', models.ManyToManyField(related_name='planes', to='catalogo.modelsplanes')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
