# Generated by Django 5.1.2 on 2025-01-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsproduct',
            name='slug_product',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
