# Generated by Django 5.1.2 on 2025-01-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsplanes',
            name='name_plan',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre Plan'),
        ),
        migrations.AlterField(
            model_name='modelsplanes',
            name='state_plan',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modelsproduct',
            name='name_product',
            field=models.CharField(max_length=155, unique=True, verbose_name='Nombre Producto'),
        ),
        migrations.AlterField(
            model_name='modelsproduct',
            name='price_product',
            field=models.FloatField(verbose_name='Precio Producto'),
        ),
        migrations.AlterField(
            model_name='modelsproduct',
            name='state_product',
            field=models.BooleanField(default=True),
        ),
    ]
