# Generated by Django 5.1.5 on 2025-02-05 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_modelsurnas_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsurnas',
            name='product_urna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urnas', to='catalogo.modelsproduct'),
        ),
    ]
