# Generated by Django 5.1.5 on 2025-02-04 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_modelsproduct_slug_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsUrnas',
            fields=[
                ('modelsproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogo.modelsproduct')),
                ('material_urna', models.CharField(choices=[('METAL', 'METAL'), ('MADERA', 'MADERA'), ('MARMOL', 'MARMOL')], default='MADERA', max_length=10, verbose_name='Material Urna')),
                ('slug_urna', models.SlugField(blank=True, max_length=255, unique=True)),
                ('state_urna', models.BooleanField(default=True)),
                ('date_create_urna', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Urna',
                'verbose_name_plural': 'Urnas',
            },
            bases=('catalogo.modelsproduct',),
        ),
        migrations.RemoveField(
            model_name='modelsproduct',
            name='category_product',
        ),
    ]
