# Generated by Django 5.1.2 on 2025-01-08 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_modelsplanes_name_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsproduct',
            name='planes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_planes', to='catalogo.modelsplanes'),
        ),
    ]
