# Generated by Django 5.1.2 on 2025-01-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_modelsproduct_planes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelsproduct',
            name='planes',
        ),
        migrations.AddField(
            model_name='modelsproduct',
            name='planes',
            field=models.ManyToManyField(null=True, related_name='key_planes', to='catalogo.modelsplanes'),
        ),
    ]
