# Generated by Django 5.1.2 on 2024-12-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsFunerarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_funeraria', models.ImageField(upload_to='Fotos Funerarias')),
                ('nombre_funeraria', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=155)),
                ('redes_sociales', models.URLField()),
                ('estado', models.BooleanField(default=True)),
                ('date_create', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Funeraria',
                'verbose_name_plural': 'Funerarias',
            },
        ),
        migrations.CreateModel(
            name='ModelsInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_institucion', models.ImageField(upload_to='Fotos Instituciones')),
                ('nombre_institucion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=155)),
                ('redes_sociales', models.URLField()),
                ('estado', models.BooleanField(default=True)),
                ('date_create', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
            },
        ),
    ]
