# Generated by Django 5.1.2 on 2024-12-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelsfamiliar',
            options={'verbose_name': 'Familiare', 'verbose_name_plural': 'Familiares'},
        ),
        migrations.AddField(
            model_name='modelsfamiliar',
            name='number_document',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='modelsfamiliar',
            name='identify_document',
            field=models.CharField(choices=[('DNI', 'DNI'), ('PST', 'PASAPORTE')], max_length=3),
        ),
    ]
