# Generated by Django 5.1.2 on 2024-12-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0003_alter_modelsfamiliar_number_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsfamiliar',
            name='estado',
            field=models.BooleanField(default=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='modelsfamiliar',
            name='number_document',
            field=models.IntegerField(null=True),
        ),
    ]
