# Generated by Django 5.1.2 on 2025-01-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_companyconf_gmail_company_companyconf_slogan_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyconf',
            name='social_networks',
        ),
    ]
