# Generated by Django 5.1.2 on 2025-01-04 14:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_socialnetworks_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyconf',
            name='address_company',
            field=models.CharField(max_length=255, verbose_name='Dirección Empresa'),
        ),
        migrations.AlterField(
            model_name='companyconf',
            name='gmail_company',
            field=models.EmailField(default='company@gmail.com', max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='companyconf',
            name='name_company',
            field=models.CharField(max_length=255, verbose_name='Nombre Empresa'),
        ),
        migrations.AlterField(
            model_name='companyconf',
            name='phone_company',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='companyconf',
            name='slogan_company',
            field=models.TextField(default='Lorem Ipsum', verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='socialnetworks',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='configuracion.companyconf'),
        ),
    ]
